### ISSUE TITLE
Missing dependencies: maia_chess_backend and haibrid_chess_utils

### ISSUE THREAD

**Issue by kennyfrc** [CSSLab/maia-chess#10]
Hi There!

I wanted to replicate some of your work; but I noticed that many of the data generators require a library called `haibrid_chess_utils` or `maia_chess_backend` in past commits. I was wondering if you were open to share this as well to the community?

**Comment by reidmcy** [comment]
Hi Kenn,

We changed the namespace to ensure the code in this repo doesn't rely on any on our internal library (`haibrid_chess_utils`) code, when verifying it all would work on other people's machines. The internal code is not useful to the community, there are over 2,000 commits stretching back to early 2019 most of which is related to dead ends and hyperparameter exploration. We also have private keys and other non-releasable data in the internal version so releasing it raw is not an option.

If you have specific questions about our methods I'll try to answer, either through Github, or you can email me (the address at the bottom of maiachess.com goes to me)

Reid

P.S. we are hoping to publish another paper soon with new methods, and that will have a corresponding code release containing improvements I've made since this release.

**Comment by iurimatias** [comment]
The readme replication instructions [here](https://github.com/CSSLab/maia-chess#replication) ask to run `move_prediction/replication-generate_pgns.sh`

that file calls [/data_generators/extractELOrange.py](https://github.com/CSSLab/maia-chess/blob/master/data_generators/extractELOrange.py) which imports `haibrid_chess_utils` so without that library it's not possible to replicate, at least by following the README own instructions.

**Comment by reidmcy** [comment]
That should be /move_prediction/replication-extractELOrange.py as that's the updated version. Also changing `haibrid_chess_utils` to `maia_chess_backend`  might even work for /data_generators/extractELOrange.py

**Comment by nmwitzig** [comment]
Hi Reid,

thanks for uploading the Weights of the Blunder Prediction Models today! However, when I try to `torch.load()` the weights python tells me that I need `haibrid_chess_utils` as well. I did import `maia_chess_backend`. Any thoughts on how to load the weights  anyway? Just using pythons `open()` did of course not yield anything sensible.

Thank you very much in advance!
Niklas

**Comment by reidmcy** [comment]
`torch.load()` uses pickle so you can fix the loading issue by renaming things to match what it expects, blunder_prediction/maia_chess_backend/torch/models.py has the model design

**Comment by nmwitzig** [comment]
Hi Reid,

thank you for your very quick response! I'm sorry, but what do you exactly mean by renaming things? What do I need to rename? The names of the layers? If yes, are those different than what you stored in `new_models.py`?

Because I just used your `NetFromConfigNew` function from `new_model.py` together with the (e.g.) `"configs/leela_blunder_00001.yaml`. If I do `leela_blunder.load_state_dict(torch.load("leela_blunder_00001-266000.pt"))` I get the same error as described above.

What do I miss?

Thank you very much!
Niklas

**Comment by reidmcy** [comment]
Pickle uses the python import system to find stuff that's missing. You can rename stuff on your python path, or use something like awk to rename stuff inside the pickle. So it's probably just `maia_chess_backend -> haibrid_chess_utils`, and the pickle docs should have more information

**Comment by nmwitzig** [comment]
Hi Reid,

thanks for your additional help. Indeed, renaming maia_chess_backend (and its references) did the trick for me!

Thank you!
