### ISSUE TITLE
Questions about centipawn score/win probability estimation

### ISSUE THREAD

**Issue by jayelm** [CSSLab/maia-chess#23]
Thanks for the great work and for the processed Lichess CSVs! I have a few questions about centipawn scores/win probabilities:

- Some of the centipawn values in the CSVs have the value `None`. What does this indicate?
- Why did you decide to predict empirical win probability, vs simply predicting the raw cp score?
- Is there a place I can retrieve the mapping from cp -> empirical win probability as reported in Fig 11 of the paper?
- Also curious if the task of predicting win probability as an auxiliary task *improved move prediction performance* versus just training on the move prediction task alone. Did you explore this?

**Comment by jayelm** [comment]
Also, is there a place I can retrieve the mapping from centipawn score -> empirical win probability as reported in Fig 11 of the paper?

**Comment by reidmcy** [comment]
Hi,

Thanks for being interested in the project. To answer your questions in order:

+ We use the Lichess CP scores, which Lichess gets from Stockfish, but they don't run SF on all games so you end up with null entries when we don't have SF evaluations
+ CP from Lichess's Stockfish does not have a well defined range: it has both a large range of numerical values and a set of categoricals (e.g. mate in n), plus it is non-linear and non-deterministic. The winrate is an attempt to normalize the CP into a range that's more tractable to deep learning. This is also why we when we run SF we have to do a fixed depth search with no caching
+ I've added the mapping to the repo [here](https://github.com/CSSLab/maia-chess/blob/master/blunder_prediction/cp_to_winrate.py), we just used a simple lookup table in our work. You could get a more precise mapping by analysing a few months of the Lichess database and running curve fit
+ Our models do predict win probability since they also have a value head, thanks to maintaining compatibility with the Leela format. We tested training with the value head loss multiplicative factor (default 1) set low (0.1) and zero during exploration. It didn't change move prediction accuracy noticeably on either condition. I will note that in _some_ of my current work I have found a small improvement if the value head is removed during training, equivalent to the multiplier of 0 condition

Hope this clears things up,
Reid
