### ISSUE TITLE
Does the version of Lc0 matter?

### ISSUE THREAD

**Issue by JotaGreen** [CSSLab/maia-chess#24]
From the code it appears you used Leela version 0.23 when doing the experiments reported on the paper. If a newer version of Leela is used, could this change the moves predicted by the Maia networks?

**Comment by reidmcy** [comment]
The newer versions I have tested did not show any changes. The Leela team are good at managing versions so I don't expect newer versions to change behaviour, them no longer maintaining compatibility is a much more likely possibility. We also don't use search (`node 1`) so changes in the search algorithm should not effect the outputs. We also have the snapshot of lc0 available so that will always be an option.
