### ISSUE TITLE
Maia taking exceedingly long time on a move

### ISSUE THREAD

**Issue by arvyy** [CSSLab/maia-chess#28]
I've played a few games recently against maia5

https://lichess.org/B4v64i5A -- it took 11 minutes to think on move 18 in a 10 minute (with increment) game. It almost timed out, but it did come back
https://lichess.org/zs9em2eO -- took 10 minutes on last move and timed out; again, 10 minute + increment game.

While first I guess could be vaguely attributed to time management (but still suspicious), there is certainly something outright wrong with second one. In both cases while waiting, I did check currently played other games by maia5, and it was making moves in timely manner, so it wasn't something to do with server going down or such. The issue doesn't seem to be necessarily related to position; challenging the bot from same position again worked fine

**Comment by reidmcy** [comment]
Thanks for telling us. There's hard coded a max move time so it isn't supposed to happen. 

There was some kind of connection issue but I'm not able to reproduce it so I'm not sure what caused that. The other bots have also had some timeouts so I suspect its due to changes on the Lichess side, but if keeps happening I'll look into it more.
