### ISSUE TITLE
Maia for Slow chess games

### ISSUE THREAD

**Issue by Makragic** [CSSLab/maia-chess#29]
Hi folks, I recently found out about this project and it is amazing.

However, one thing stops me from playing against Maia on Lichess - I play slow games, 45|45 or 90|30. Maia currently doesn't play like a slow chess player, it "thinks" for 30 seconds to a minute per move which is not something that slow chess player would do. Often times it ends up with more time on the clock than it started with. 

The problem with this is that it changes the game, it changes the thinking from my part - I've also consulted with people from my chess club and they all agree. You spend couple of minutes, perhaps 10 minute for the most important moves, and it is not normal behavior that you have to stress your brain on that level once again in 30 seconds.

Do you have plans to focus on time management in future releases?

**Comment by reidmcy** [comment]
Hi,

Thanks for enjoying the bots. We have debated internally about what updates to make the the bots and are more likely to release new bots (I've been trying to get them finalized all summer) on new accounts than make large changes to the current ones.

What you are asking about is large change, since unfortunately, all moves take the same amount of "effort" for the bots. The current system uses a basic model to try and predict the difficulty but isn't very good so we put limits how much time it can take, you don't want to wait 10 minutes for a response to _e4_. The newer designs we have been testing can better model the time taken but we don't try to do it for the time controls you're talking about since there aren't enough games (since they take so long to play). 

So we should do better in the future, but probably will still have issues with high time controls.
