### ISSUE TITLE
Accuracy Elaboration

### ISSUE THREAD

**Issue by itaybardan** [CSSLab/maia-chess#44]
Hi guys, 

Can you elaborate on how you received Maia's accuracy numbers? or show me where is the script that calculates that?
What are the steps for reproducing the same results on my computer?

Thanks!

**Comment by reidmcy** [comment]
We used `lc0` for running the models and ran it on the dataset discussed in the [README](https://github.com/CSSLab/maia-chess#replication). Then removed positions that were low on time or in the early game, check the paper for more details on the exact criteria.

I've just pushed the script we ran ([replication-run_model_on_csv.py](https://github.com/CSSLab/maia-chess/blob/master/move_prediction/replication-run_model_on_csv.py)), it might take some fiddling to run since it is based on a old version of `python-chess` and requires `lc0` setup in the right way. So you can take a look at that if it helps.
