### ISSUE TITLE
Nets

### ISSUE THREAD

**Issue by Stealmator** [CSSLab/maia-chess#67]
I have two questions: 

Is that project stopped?

and the nets in the github were not same as lichess ones (probably didnt updated)

**Comment by reidmcy** [comment]
The project is very active, we have a recent publication out at ICLR, a couple upcoming posters at IC2S2, and have multiple papers and projects ongoing.

The nets here are what we use for the Lichess bots, I actually copied them from this repo since it's the easiest place to get them. We use a simple opening book to randomize the openings then the public weights.
