### ISSUE TITLE
How are you modeling move sequences leading up to the current position?

### ISSUE THREAD

**Issue by EaswarGn** [CSSLab/maia-chess#69]
In your paper I read that one of the biggest changes you made to Maia compared to Leela is that you incorporated move history (the last 6 moves made by each player). But I couldn't find in the paper how exactly you modeled this move history and I couldn't find any trace of this in the codebase. Please show me where you incorporated this in your code (what kind of model did you use) and how it works.

Thank you very much.

**Comment by reidmcy** [comment]
We did the same input representation as lc0. That's how we get compatibility with their model format. We just use the same representation for each board in the history, they're all part of the input stack. That's why it's 112 channels, here's where the input is defined: https://github.com/CSSLab/maia-chess/blob/master/move_prediction/maia_chess_backend/maia/tfprocess.py#L137

**Comment by EaswarGn** [comment]
Just curious how much RAM did you use to train your model and how long did it take?

**Comment by reidmcy** [comment]
We weren't RAM (or GPU memory) limited. The models are small by CNN standards, our limitation was on GPU speed. The computation was done on the NC6/12/24 line of azure VMs, so well below 56GB.
